"use client";

import { CalendarClock, CalendarPlus, CheckCircle2, CircleAlert, Clock3, LogIn, LogOut, ShieldCheck } from "lucide-react";
import { useActionState } from "react";
import { formatMinorUnits, minorUnitsToMajor } from "@/domain/money/minor-units";
import { useCommandForm } from "@/features/shared/use-command-form";
import type { BookingDraftAction, BookingDraftOption } from "./booking-draft-form";
import { BookingDraftForm } from "./booking-draft-form";

export type BookingApprovalStatus = "pending" | "approved" | "rejected" | "expired" | "executed" | null;
export type BookingDraftListItem = Readonly<{
  id: string; propertyId: string; propertyLabel: string; clientId: string; clientLabel: string;
  status: "draft" | "pending_approval" | "confirmed" | "checked_in" | "checked_out" | "cancelled" | "completed";
  checkIn: string; checkOut: string; amountMinor: string | null; currency: string | null;
  commercialCompletionStatus: "complete" | "needs_completion"; version: number; hasCheckIn: boolean; hasCheckOut: boolean;
  confirmationApprovalStatus: BookingApprovalStatus; amendmentApprovalStatus: BookingApprovalStatus; cancellationApprovalStatus: BookingApprovalStatus;
  createdAt: string;
}>;

export type BookingLifecycleActionState = Readonly<{ status: "idle" | "success" | "invalid" | "denied" | "retry"; message: string }>;
export type BookingLifecycleAction = (previousState: BookingLifecycleActionState, formData: FormData) => Promise<BookingLifecycleActionState>;
const initialState: BookingLifecycleActionState = { status: "idle", message: "" };
const statusCopy: Record<BookingDraftListItem["status"], { label: string; tone: string }> = {
  draft: { label: "مسودة", tone: "bg-[#fff8e9] text-[#85652e]" }, pending_approval: { label: "في انتظار الاعتماد", tone: "bg-[#fff6e8] text-[#9a6519]" }, confirmed: { label: "مؤكدة", tone: "bg-[#edf8f4] text-tide" }, cancelled: { label: "ملغاة", tone: "bg-[#f1f0ed] text-muted" }, completed: { label: "مكتملة", tone: "bg-[#edf8f4] text-tide" }, checked_in: { label: "داخل الإقامة", tone: "bg-[#edf8f4] text-tide" }, checked_out: { label: "تمت المغادرة", tone: "bg-[#edf8f4] text-tide" },
};
function formatDate(value: string) { return new Intl.DateTimeFormat("ar-EG", { day: "numeric", month: "short" }).format(new Date(value)); }
function ActionFeedback({ state }: Readonly<{ state: BookingLifecycleActionState }>) { return state.status === "idle" || !state.message ? null : <p aria-live="polite" className={`mt-2 text-[11px] font-semibold ${state.status === "success" ? "text-tide" : state.status === "denied" ? "text-coral" : "text-[#85652e]"}`}><CircleAlert aria-hidden="true" className="me-1 inline size-3.5" />{state.message}</p>; }

function SimpleCommand({ bookingId, label, action, emphasis = false, extra = {} }: Readonly<{ bookingId: string; label: string; action: BookingLifecycleAction; emphasis?: boolean; extra?: Record<string, string> }>) {
  const [state, formAction, pending] = useActionState(action, initialState); const { formRef, idempotencyKey } = useCommandForm(state);
  return <form action={formAction} ref={formRef}><input name="booking_id" type="hidden" value={bookingId} /><input name="idempotency_key" type="hidden" value={idempotencyKey} />{Object.entries(extra).map(([name, value]) => <input key={name} name={name} type="hidden" value={value} />)}<button className={`inline-flex min-h-10 items-center gap-1.5 rounded-xl px-3 text-[11px] font-bold disabled:opacity-50 ${emphasis ? "bg-tide text-white hover:bg-harbor" : "border border-[#d8c9a4] bg-white text-[#85652e] hover:bg-[#fff8e9]"}`} disabled={pending} type="submit">{emphasis ? <CheckCircle2 aria-hidden="true" className="size-3.5" /> : <ShieldCheck aria-hidden="true" className="size-3.5" />}{label}</button><ActionFeedback state={state} /></form>;
}

function ReasonCommand({ bookingId, label, action }: Readonly<{ bookingId: string; label: string; action: BookingLifecycleAction }>) {
  const [state, formAction, pending] = useActionState(action, initialState); const { formRef, idempotencyKey } = useCommandForm(state);
  return <details className="rounded-xl border border-[#ead9b8] bg-[#fffdf8] p-2"><summary className="cursor-pointer text-[11px] font-bold text-[#85652e]">{label}</summary><form action={formAction} className="mt-2 space-y-2" ref={formRef}><input name="booking_id" type="hidden" value={bookingId} /><input name="idempotency_key" type="hidden" value={idempotencyKey} /><textarea className="min-h-20 w-full rounded-lg border border-[#d8c9a4] bg-white p-2 text-xs" maxLength={1000} name="reason" placeholder="سبب واضح" required /><button className="rounded-lg bg-harbor px-3 py-2 text-[11px] font-bold text-white disabled:opacity-50" disabled={pending} type="submit">تأكيد الطلب</button><ActionFeedback state={state} /></form></details>;
}

function SnapshotCompletion({ bookingId, currency, action }: Readonly<{ bookingId: string; currency: string; action: BookingLifecycleAction }>) {
  const [state, formAction, pending] = useActionState(action, initialState); const { formRef, idempotencyKey } = useCommandForm(state);
  return <details className="w-full rounded-xl border border-[#ead9b8] bg-[#fff8e9] p-3"><summary className="cursor-pointer text-[11px] font-bold text-[#85652e]">استكمال السعر التاريخي</summary><form action={formAction} className="mt-3 grid gap-2 sm:grid-cols-2" ref={formRef}><input name="booking_id" type="hidden" value={bookingId} /><input name="currency" type="hidden" value={currency} /><input name="idempotency_key" type="hidden" value={idempotencyKey} /><input className="rounded-lg border border-[#d8c9a4] bg-white p-2 text-xs" inputMode="decimal" name="amount" placeholder={`المبلغ (${currency})`} required /><input className="rounded-lg border border-[#d8c9a4] bg-white p-2 text-xs" name="reason" placeholder="مصدر/سبب استكمال السعر" required /><button className="rounded-lg bg-harbor px-3 py-2 text-[11px] font-bold text-white disabled:opacity-50 sm:col-span-2" disabled={pending} type="submit">حفظ snapshot</button><ActionFeedback state={state} /></form></details>;
}

function AmendmentForm({ booking, properties, clients, action }: Readonly<{ booking: BookingDraftListItem; properties: readonly BookingDraftOption[]; clients: readonly BookingDraftOption[]; action: BookingLifecycleAction }>) {
  const [state, formAction, pending] = useActionState(action, initialState); const { formRef, idempotencyKey } = useCommandForm(state); const checkedIn = booking.status === "checked_in"; const currency = booking.currency ?? "EGP"; const amount = booking.amountMinor ? minorUnitsToMajor(booking.amountMinor, currency) : "";
  return <details className="w-full rounded-xl border border-[#d6e3dd] bg-[#f7fbf9] p-3"><summary className="cursor-pointer text-[11px] font-bold text-tide">طلب تعديل الحجز</summary><form action={formAction} className="mt-3 grid gap-2 sm:grid-cols-2" ref={formRef}><input name="booking_id" type="hidden" value={booking.id} /><input name="currency" type="hidden" value={currency} /><input name="idempotency_key" type="hidden" value={idempotencyKey} />
    {checkedIn ? <><input name="property_id" type="hidden" value={booking.propertyId} /><input name="client_id" type="hidden" value={booking.clientId} /><input name="check_in" type="hidden" value={booking.checkIn} /><div className="rounded-lg bg-white p-2 text-[11px] text-muted sm:col-span-2">بعد الوصول: العقار والعميل وتاريخ الوصول مجمّدة. يمكن تعديل المغادرة والمبلغ فقط عبر الاعتماد.</div></> : <><select className="rounded-lg border border-[#c9d9d3] bg-white p-2 text-xs" defaultValue={booking.propertyId} name="property_id" required>{properties.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select><select className="rounded-lg border border-[#c9d9d3] bg-white p-2 text-xs" defaultValue={booking.clientId} name="client_id" required>{clients.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select><input className="rounded-lg border border-[#c9d9d3] bg-white p-2 text-xs" defaultValue={booking.checkIn} name="check_in" required type="date" /></>}
    <input className="rounded-lg border border-[#c9d9d3] bg-white p-2 text-xs" defaultValue={booking.checkOut} name="check_out" required type="date" /><input className="rounded-lg border border-[#c9d9d3] bg-white p-2 text-xs" defaultValue={amount} inputMode="decimal" name="amount" required /><input className="rounded-lg border border-[#c9d9d3] bg-white p-2 text-xs" name="reason" placeholder="سبب التعديل" required /><button className="rounded-lg bg-harbor px-3 py-2 text-[11px] font-bold text-white disabled:opacity-50 sm:col-span-2" disabled={pending} type="submit">إرسال التعديل للاعتماد</button><ActionFeedback state={state} /></form></details>;
}

function BookingCard({ booking, properties, clients, actions, permissions, defaultCurrency }: Readonly<{ booking: BookingDraftListItem; properties: readonly BookingDraftOption[]; clients: readonly BookingDraftOption[]; actions: BookingPageActions; permissions: BookingPermissions; defaultCurrency: string }>) {
  const status = statusCopy[booking.status]; const amount = booking.amountMinor && booking.currency ? formatMinorUnits(booking.amountMinor, booking.currency) : null; const mutableStay = booking.status === "confirmed" || booking.status === "checked_in";
  return <article className="rounded-2xl border border-[#e5e9e4] bg-[#fcfdfb] p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-extrabold text-[#173d35]">{booking.propertyLabel}</p><p className="mt-1 text-xs text-[#71817b]">{booking.clientLabel}</p></div><span className={`inline-flex shrink-0 items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-bold ${status.tone}`}><Clock3 aria-hidden="true" className="size-3" />{status.label}</span></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-[#e7ebe6] pt-3 text-[11px] text-[#71817b]"><span className="font-mono" dir="ltr">{booking.checkIn} → {booking.checkOut}</span><span>{amount ? `${amount} ${booking.currency}` : "السعر يحتاج استكمالًا"}</span><time dateTime={booking.createdAt}>{formatDate(booking.createdAt)}</time></div>
    <div className="mt-4 flex flex-wrap gap-2">{booking.status === "draft" && booking.commercialCompletionStatus === "complete" && permissions.canRequestChanges ? <SimpleCommand action={actions.requestApproval} bookingId={booking.id} label="طلب اعتماد" /> : null}{booking.status === "pending_approval" && booking.confirmationApprovalStatus === "pending" ? <span className="inline-flex min-h-10 items-center gap-1.5 rounded-xl border border-[#e3d6b9] bg-[#fff8e9] px-3 text-[11px] font-bold text-[#85652e]"><Clock3 aria-hidden="true" className="size-3.5" />بانتظار قرار المالك أو المدير</span> : null}{booking.status === "pending_approval" && booking.confirmationApprovalStatus === "expired" && permissions.canRequestChanges ? <SimpleCommand action={actions.requestApproval} bookingId={booking.id} label="تجديد طلب الاعتماد" /> : null}{booking.status === "pending_approval" && booking.confirmationApprovalStatus === "approved" && permissions.canExecuteChanges ? <SimpleCommand action={actions.confirm} bookingId={booking.id} emphasis label="تنفيذ التأكيد المعتمد" /> : null}{booking.status === "draft" && permissions.canRequestChanges ? <ReasonCommand action={actions.cancelDraft} bookingId={booking.id} label="إلغاء المسودة" /> : null}
      {booking.commercialCompletionStatus === "needs_completion" && permissions.canCompleteSnapshot ? <SnapshotCompletion action={actions.completeSnapshot} bookingId={booking.id} currency={defaultCurrency} /> : null}
      {mutableStay && permissions.canRequestChanges && !["pending", "approved"].includes(booking.amendmentApprovalStatus ?? "") ? <AmendmentForm action={actions.requestAmendment} booking={booking} clients={clients} properties={properties} /> : null}{mutableStay && booking.amendmentApprovalStatus === "pending" ? <span className="rounded-xl bg-[#fff8e9] px-3 py-2 text-[11px] font-bold text-[#85652e]">تعديل بانتظار الاعتماد</span> : null}{mutableStay && booking.amendmentApprovalStatus === "approved" && permissions.canExecuteChanges ? <SimpleCommand action={actions.executeAmendment} bookingId={booking.id} emphasis label="تنفيذ التعديل المعتمد" /> : null}
      {mutableStay && permissions.canRequestChanges && !["pending", "approved"].includes(booking.cancellationApprovalStatus ?? "") ? <ReasonCommand action={actions.requestCancellation} bookingId={booking.id} label="طلب إلغاء الحجز" /> : null}{mutableStay && booking.cancellationApprovalStatus === "pending" ? <span className="rounded-xl bg-[#fff8e9] px-3 py-2 text-[11px] font-bold text-[#85652e]">إلغاء بانتظار الاعتماد</span> : null}{mutableStay && booking.cancellationApprovalStatus === "approved" && permissions.canExecuteChanges ? <SimpleCommand action={actions.executeCancellation} bookingId={booking.id} emphasis label="تنفيذ الإلغاء المعتمد" /> : null}
      {booking.status === "confirmed" && permissions.canOperateStay && !booking.hasCheckIn ? <SimpleCommand action={actions.recordStay} bookingId={booking.id} emphasis extra={{ event_type: "check_in" }} label="تسجيل الوصول" /> : null}{booking.status === "checked_in" && permissions.canOperateStay && !booking.hasCheckOut ? <SimpleCommand action={actions.recordStay} bookingId={booking.id} emphasis extra={{ event_type: "check_out" }} label="تسجيل المغادرة" /> : null}
    </div></article>;
}

type BookingPageActions = Readonly<{ createDraft: BookingDraftAction; requestApproval: BookingLifecycleAction; confirm: BookingLifecycleAction; cancelDraft: BookingLifecycleAction; completeSnapshot: BookingLifecycleAction; requestAmendment: BookingLifecycleAction; executeAmendment: BookingLifecycleAction; requestCancellation: BookingLifecycleAction; executeCancellation: BookingLifecycleAction; recordStay: BookingLifecycleAction }>;
type BookingPermissions = Readonly<{ canCreate: boolean; canRequestChanges: boolean; canExecuteChanges: boolean; canCompleteSnapshot: boolean; canOperateStay: boolean }>;

export function BookingsPage({ properties, clients, drafts, currency, actions, permissions }: Readonly<{ properties: readonly BookingDraftOption[]; clients: readonly BookingDraftOption[]; drafts: readonly BookingDraftListItem[]; currency: string; actions: BookingPageActions; permissions: BookingPermissions }>) {
  const active = drafts.filter((booking) => !["completed", "checked_out", "cancelled"].includes(booking.status)).length;
  return <main className="min-h-[calc(100vh-74px)] bg-[#fbfaf7] px-4 py-6 text-[#172a28] sm:px-7 sm:py-8 lg:px-9 lg:py-10"><div className="mx-auto max-w-[1120px]"><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold text-[#a2742d]">سير عمل الإقامة التجاري</p><h1 className="mt-3 text-3xl font-extrabold tracking-[-0.09em] text-[#173d35] sm:text-4xl">الإقامات والحجوزات</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-[#687b74]">الإنشاء والتعديل والإلغاء والتأكيد عبر مسارات اعتماد واضحة، مع سعر محفوظ بوحدات نقدية دقيقة.</p></div><div className="flex items-center gap-2 rounded-full border border-[#cfe3d9] bg-[#eef7f2] px-3 py-2 text-[11px] font-bold text-[#1a6958]"><CalendarClock aria-hidden="true" className="size-4" />{active} عمليات نشطة</div></header><div className={`mt-8 grid gap-6 ${permissions.canCreate ? "xl:grid-cols-[minmax(0,0.88fr)_minmax(0,1.12fr)]" : ""}`}>{permissions.canCreate ? <BookingDraftForm clients={clients} createDraft={actions.createDraft} currency={currency} properties={properties} /> : null}<section aria-labelledby="booking-queue-heading" className="rounded-[1.75rem] border border-[#e1e5df] bg-white p-5 shadow-[0_10px_24px_rgba(26,52,45,0.035)] sm:p-7"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-[#1a6958]"><CalendarPlus aria-hidden="true" className="size-4" /><span className="text-[11px] font-bold">قائمة المتابعة</span></div><h2 className="mt-2 text-xl font-extrabold tracking-[-0.07em] text-[#173d35]" id="booking-queue-heading">آخر الإقامات</h2></div><span className="grid size-9 place-items-center rounded-xl bg-[#eef7f2] font-mono text-sm font-bold text-[#1a6958]">{drafts.length}</span></div>{drafts.length === 0 ? <div className="mt-7 rounded-2xl border border-dashed border-[#cfd9d2] bg-[#fcfdfb] px-5 py-12 text-center"><CalendarClock aria-hidden="true" className="mx-auto size-6 text-[#1a6958]" /><h3 className="mt-4 text-base font-extrabold text-[#173d35]">لا توجد إقامات بعد</h3></div> : <div className="mt-6 space-y-3">{drafts.map((booking) => <BookingCard actions={actions} booking={booking} clients={clients} defaultCurrency={currency} key={booking.id} permissions={permissions} properties={properties} />)}</div>}<div className="mt-6 flex items-center gap-2 border-t border-[#e7ebe6] pt-4 text-[11px] text-[#71817b]"><CircleAlert aria-hidden="true" className="size-4 text-[#1a6958]" />المبلغ المتفق عليه snapshot تجاري فقط؛ لا توجد دفعات أو refunds أو ledger في V1.</div></section></div></div></main>;
}
