import { CalendarRange, ShieldCheck, Wrench } from "lucide-react";
import { AvailabilityBlockCreateForm, type AvailabilityBlockAction, type AvailabilityPropertyOption } from "./availability-block-create-form";

export type AvailabilityBlockListItem = Readonly<{ id: string; propertyLabel: string; startDate: string; endDate: string; blockType: "maintenance" | "owner_use" | "administrative"; reason: string | null }>;
const typeCopy = { maintenance: "صيانة", owner_use: "استخدام المالك", administrative: "إداري" } as const;

export function AvailabilityBlocksPage({ blocks, properties, createBlock }: Readonly<{ blocks: readonly AvailabilityBlockListItem[]; properties: readonly AvailabilityPropertyOption[]; createBlock?: AvailabilityBlockAction }>) {
  return <main className="min-h-screen bg-canvas px-4 py-5 text-ink sm:px-8 sm:py-8 lg:px-12"><div className="mx-auto max-w-5xl"><header className="rounded-[2rem] border border-[#d4dfda] bg-[#f0f7f4] px-6 py-7 shadow-[0_18px_44px_rgba(16,33,38,0.05)] sm:px-9 sm:py-9"><div className="flex flex-wrap items-start justify-between gap-5"><div className="flex gap-4"><div className="grid size-12 place-items-center rounded-2xl bg-harbor text-sea-glass"><CalendarRange aria-hidden="true" className="size-6" /></div><div><p className="text-[11px] font-bold tracking-[0.08em] text-tide">خط التشغيل</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.09em] text-harbor sm:text-4xl">حظر التوفر</h1><p className="mt-3 max-w-xl text-sm leading-7 text-muted">النطاقات اليدوية التي تمنع توافر العقار. لا يمكن أن تتجاوز حجزاً مؤكداً.</p></div></div><div className="flex items-center gap-2 rounded-xl border border-[#d4dfda] bg-white/70 px-3 py-2 text-[11px] font-semibold text-tide"><ShieldCheck aria-hidden="true" className="size-4" />دفتر إشغال موحّد</div></div><div className="mt-7 flex items-end gap-3 border-t border-[#d4dfda] pt-5"><strong className="font-mono text-4xl font-medium tracking-[-0.09em] text-harbor">{blocks.length}</strong><span className="pb-1 text-xs text-muted">حظر مسجل</span></div></header>{createBlock ? <div className="mt-6"><AvailabilityBlockCreateForm createBlock={createBlock} properties={properties} /></div> : null}{blocks.length === 0 ? <section className="mt-6 rounded-[1.75rem] border border-dashed border-[#bfd1cb] bg-surface px-6 py-14 text-center"><Wrench aria-hidden="true" className="mx-auto size-6 text-tide" /><h2 className="mt-5 text-xl font-bold text-harbor">لا توجد نطاقات محظورة</h2></section> : <section aria-label="خط حظر التوفر" className="mt-6 space-y-3">{blocks.map((block) => <article className="relative overflow-hidden rounded-[1.5rem] border border-line bg-surface p-5 shadow-[0_10px_28px_rgba(16,33,38,0.035)]" key={block.id}><span className="absolute right-0 top-0 h-full w-1.5 bg-tide" /><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-semibold tracking-[0.08em] text-tide">{typeCopy[block.blockType]}</p><h2 className="mt-2 text-lg font-bold text-harbor">{block.propertyLabel}</h2></div><div className="rounded-xl bg-[#edf8f4] px-3 py-2 font-mono text-xs text-harbor"><time dateTime={block.startDate}>{block.startDate}</time><span className="mx-2 text-muted">←</span><time dateTime={block.endDate}>{block.endDate}</time></div></div>{block.reason ? <p className="mt-4 border-t border-line pt-3 text-sm leading-6 text-muted">{block.reason}</p> : null}</article>)}</section>}</div></main>;
}
