import { Bell, BellRing, Check } from "lucide-react";

export type NotificationItem = Readonly<{ id: string; category: "operational" | "approval" | "finance" | "security" | "system"; title: string; body: string; readAt: string | null; createdAt: string }>;
export type MarkNotificationRead = (notificationId: string) => Promise<void>;
function formatDate(value: string) { return new Intl.DateTimeFormat("ar-EG", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }

export function NotificationsPage({ notifications, markRead }: Readonly<{ notifications: readonly NotificationItem[]; markRead: MarkNotificationRead }>) {
  return <main className="min-h-screen bg-canvas px-4 py-5 text-ink sm:px-8 sm:py-8 lg:px-12"><div className="mx-auto max-w-4xl"><header className="rounded-[2rem] border border-[#d4dfda] bg-[#f0f7f4] px-6 py-7 shadow-[0_18px_44px_rgba(16,33,38,0.05)] sm:px-9 sm:py-9"><div className="flex gap-4"><div className="grid size-12 place-items-center rounded-2xl bg-harbor text-sea-glass"><Bell aria-hidden="true" className="size-6" /></div><div><p className="text-[11px] font-bold tracking-[0.08em] text-tide">صندوق المؤسسة</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.09em] text-harbor sm:text-4xl">الإشعارات</h1><p className="mt-3 max-w-xl text-sm leading-7 text-muted">رسائل داخل التطبيق مخصصة لك. لا تتضمن هذه الشاشة قنوات إرسال خارجية.</p></div></div></header>{notifications.length === 0 ? <section className="mt-6 rounded-[1.75rem] border border-dashed border-[#bfd1cb] bg-surface px-6 py-14 text-center"><Bell aria-hidden="true" className="mx-auto size-6 text-tide" /><h2 className="mt-5 text-xl font-bold text-harbor">لا توجد إشعارات حالياً</h2></section> : <section aria-label="صندوق الإشعارات" className="mt-6 space-y-3">{notifications.map((notification) => <article className={`flex items-start gap-4 rounded-[1.4rem] border p-4 shadow-[0_8px_22px_rgba(16,33,38,0.03)] ${notification.readAt ? "border-line bg-surface" : "border-[#bfd1cb] bg-[#f6fbf9]"}`} key={notification.id}><div className={`grid size-9 shrink-0 place-items-center rounded-xl ${notification.readAt ? "bg-[#f1f0ed] text-muted" : "bg-sea-glass/45 text-tide"}`}>{notification.readAt ? <Check aria-hidden="true" className="size-4" /> : <BellRing aria-hidden="true" className="size-4" />}</div><div className="min-w-0 flex-1"><h2 className="text-sm font-bold text-harbor">{notification.title}</h2><p className="mt-1 text-sm leading-6 text-muted">{notification.body}</p><time className="mt-2 block font-mono text-[10px] text-muted" dateTime={notification.createdAt}>{formatDate(notification.createdAt)}</time></div>{!notification.readAt ? <form action={markRead.bind(null, notification.id)}><button className="shrink-0 rounded-lg border border-[#bfd1cb] bg-white px-3 py-2 text-[11px] font-bold text-tide hover:bg-[#edf8f4]" type="submit">تمت القراءة</button></form> : null}</article>)}</section>}</div></main>;
}
